name: 'Deploy Frontend'
description: 'Deploys frontend to S3'

inputs:
  aws-access-key:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
  s3-bucket:
    description: 'S3 bucket name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Download build output
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        path: frontend/out
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.aws-access-key }}
        aws-secret-access-key: ${{ inputs.aws-secret-key }}
        aws-region: ${{ inputs.aws-region }}
        
    - name: Deploy to S3
      shell: bash
      run: |
        cd frontend
        # Sync all static files from the out directory
        aws s3 sync out/ s3://${{ inputs.s3-bucket }}/ --delete