name: 'Deploy Frontend'
description: 'Deploys frontend to S3'

inputs:
  aws-access-key:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
  s3-bucket:
    description: 'S3 bucket name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Download build output
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        path: frontend/.next
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.aws-access-key }}
        aws-secret-access-key: ${{ inputs.aws-secret-key }}
        aws-region: ${{ inputs.aws-region }}
        
    - name: Deploy to S3
      shell: bash
      run: |
        cd frontend
        # Sync static assets
        aws s3 sync .next/static s3://${{ inputs.s3-bucket }}/_next/static/ --delete
        
        # Sync public files
        aws s3 sync public s3://${{ inputs.s3-bucket }}/ --delete
        
        # Upload server-side rendered pages (if you're using export)
        if [ -d ".next/server/pages" ]; then
          aws s3 sync .next/server/pages s3://${{ inputs.s3-bucket }}/ --delete
        fi
        
        # For app directory routes (adjust if needed)
        if [ -d ".next/server/app" ]; then
          aws s3 sync .next/server/app s3://${{ inputs.s3-bucket }}/app/ --delete
        fi