name: 'Build Backend'
description: 'Builds the backend Docker image and pushes to Docker Hub'

inputs:
  docker-username:
    description: 'DockerHub username'
    required: true
  docker-token:
    description: 'DockerHub token'
    required: true
  image-tag:
    description: 'Tag for the Docker image'
    required: true
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-token }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Build and push backend
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: ${{ inputs.docker-username }}/citizen-connect-backend:${{ inputs.image-tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max