name: 'Build Frontend'
description: 'Builds the frontend Docker image and pushes to Docker Hub'

inputs:
  docker-username:
    description: 'DockerHub username'
    required: true
  docker-token:
    description: 'DockerHub token'
    required: true
  image-tag:
    description: 'Tag for the Docker image'
    required: true
    default: 'latest'
  backend-url:
    description: 'Backend API URL to use in the build'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-token }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        build-args: |
          NEXT_PUBLIC_BACKEND_URL=${{ inputs.backend-url }}
        push: true
        tags: ${{ inputs.docker-username }}/citizen-connect-frontend:${{ inputs.image-tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max