name: Backend CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/actions/backend-**'
      - '.github/workflows/backend.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/actions/backend-**'
  workflow_dispatch:

jobs:
  test:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'
      
      - name: Install dependencies
        run: |
          cd backend
          npm ci
          
      - name: Run Tests
        run: |
          cd backend
          npm test || echo "Warning: Tests failed but continuing deployment"
        continue-on-error: true
        
  build:
    name: Build Backend
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build and Push
        id: docker_build
        uses: ./.github/actions/backend-build
        with:
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
          image-tag: latest
    outputs:
      docker_success: ${{ steps.docker_build.outcome == 'success' }}
          
  deploy:
    name: Deploy Backend
    needs: build
    if: needs.build.outputs.docker_success == 'true' && (github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Deploy to EC2
        uses: ./.github/actions/backend-deploy
        with:
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          ec2-host: ${{ secrets.EC2_HOST }}
          ec2-username: ${{ secrets.EC2_USERNAME }}
          ec2-key: ${{ secrets.EC2_SSH_KEY }}
          rds-host: ${{ secrets.RDS_HOST }}
          rds-port: ${{ secrets.RDS_PORT }}
          rds-db-name: ${{ secrets.RDS_DB_NAME }}
          rds-username: ${{ secrets.RDS_USERNAME }}
          rds-password: ${{ secrets.RDS_PASSWORD }}
          jwt-secret: ${{ secrets.JWT_SECRET }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          image-tag: latest