name: Backend CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  test:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run Tests
        uses: ./.github/actions/backend-test
        continue-on-error: true
        
  build:
    name: Build Backend
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build and Push
        uses: ./.github/actions/backend-build
        with:
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
          image-tag: latest
          
  deploy:
    name: Deploy Backend
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Deploy to EC2
        uses: ./.github/actions/backend-deploy
        with:
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          ec2-host: ${{ secrets.EC2_HOST }}
          ec2-username: ${{ secrets.EC2_USERNAME }}
          ec2-key: ${{ secrets.EC2_SSH_KEY }}
          rds-host: ${{ secrets.RDS_HOST }}
          rds-port: ${{ secrets.RDS_PORT }}
          rds-db-name: ${{ secrets.RDS_DB_NAME }}
          rds-username: ${{ secrets.RDS_USERNAME }}
          rds-password: ${{ secrets.RDS_PASSWORD }}
          jwt-secret: ${{ secrets.JWT_SECRET }}
          image-tag: latest