name: Frontend CI/CD

on:
  push:
    branches: [main, frontend]
    paths:
      - 'frontend/**'
      - '.github/actions/frontend-**'
      - '.github/workflows/frontend.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/actions/frontend-**'
  workflow_dispatch:

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  test:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
          
      - name: Run Tests
        run: |
          cd frontend
          npm test || echo "Warning: Tests failed but continuing deployment"
        continue-on-error: true
        
  build:
    name: Build Frontend
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build
        id: build_step
        uses: ./.github/actions/frontend-build
        with:
          backend-url: ${{ secrets.BACKEND_API_URL }}
    outputs:
      build_success: ${{ steps.build_step.outcome == 'success' }}
          
  deploy:
    name: Deploy Frontend
    needs: build
    if: needs.build.outputs.build_success == 'true' && (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/frontend') || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Deploy to S3
        uses: ./.github/actions/frontend-deploy
        with:
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          s3-bucket: ${{ secrets.S3_BUCKET_NAME }}